# Generated by Django 3.1 on 2020-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('ticker', models.CharField(max_length=3)),
                ('industry', models.CharField(max_length=30)),
                ('rating', models.CharField(default='NONE', max_length=4)),
                ('index', models.CharField(max_length=30)),
                ('summary', models.TextField(default='additional info about company')),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('name', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=1)),
                ('num_of_share', models.IntegerField()),
                ('stock_price', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
